version: '2'
services:
  server:
    image: redis:3.2.8-alpine
    command: redis-server --appendonly yes
    environment:
      - SERVICE_NAME=redis
    volumes_from:
      - data
    labels:
      io.rancher.sidekicks: data
  
  data:
    image: alpine
    command: /bin/true
    volumes:
      - /data
    labels:
      io.rancher.container.start_once: true
